### PR TITLE
Add some more visualization of eliminations and transfers

### PR DESCRIPTION
**Pull request by khuey**
See this screenshot of example output (when clicking on Leno's final result). You might think the trick of having non-enumerable properties on the rounds for data that's not part of the "live" result is too clever, not sure :)

Example output

### CODE REVIEW

**Comment by khuey** [comment]
I also eventually want to show forward looking elimination data as well as "paths" taken by ballots through the ranking space eventually, but that's harder UI-wise.

**Comment by dbaron** [comment]
I was actually thinking about trying to show something similar, plus a map.

But some things I don't see here that I would have wanted are:
* encoding the selected cell in gState so that it's part of the URL, and
* showing a stronger visual indication of which cell was selected (I actually was starting with that code, and had it half-written last night)

(But pretty busy today... will hopefully look more later.)

**Comment by khuey** [comment]
I realized this morning that the backwards looking totals here are not actually correct because they don't test whether the previous vote itself was for an already eliminated candidate. In other words, if the true preference ranking is A, B, C, D, and a voter votes C, D, B, when the ballot reaches B it's counted as a transfer from D, not as a transfer from C.

**Comment by dbaron** [comment]
I think the distinction you draw between undervote and exhausted isn't meaningful.  The undervote bit on the ballot says whether than *rank* is blank, but a ballot that's blank for rank 1 and has a candidate on rank 2 isn't semantically different from the inverse -- however, your undervote counting code is treating it differently.  I think I'm going to change that.

**Comment by khuey** [comment]
I think it's interesting to see who left positions blank and who actually ranked three candidates, which I believe is the distinction that code makes.

**Comment by dbaron** [comment]
I think both my initial explanation and yours are both wrong -- neither explains (after rereading the code) how you end up with both undervotes and exhausted in the first round.

I also think the overvote/exhausted numbers should be cumulative like the other numbers.

**Comment by khuey** [comment]
Those numbers are the entries for the D8 RCV contest, I think.

Making it cumulative is probably a good idea. Then the "Total" field becomes "ballots still in play" and summing that plus the overvote/undervote/exhausted counts should be constant.

**Comment by dbaron** [comment]
>I realized this morning that the backwards looking totals here are not actually correct because they don't test whether the previous vote itself was for an already eliminated candidate. In other words, if the true preference ranking is A, B, C, D, and a voter votes C, D, B, when the ballot reaches B it's counted as a transfer from D, not as a transfer from C.

I don't actually know what you mean by this.

On the other hand, it's not clear which way to count the transfer when you've gotten to the 3rd ballot choice.  Should it count as a transfer from the 1st, from the 2nd, or from the 1st-2nd sequence.  It looks like your code counts it as a transfer from the 2nd.

**Comment by khuey** [comment]
Right. It counts it as a transfer from the 2nd rank, *even* if the 2nd rank wasn't ever actually used because it was for a candidate who was eliminated before the 1st rank candidate.

**Comment by dbaron** [comment]
OK, I fixed that, and I'm now showing both reasonable ways of counting transfers.

**Comment by dbaron** [comment]
I've also now stored the selection in gState so that it's part of the URL.  (This required a good bit of refactoring.)

**Pull request merged**
